---
name: "Graylint"
description: "Run linters and show only messages changed since a past revision."
author: "Antti Kaihola and contributors to Graylint"
inputs:
  options:
    description: >-
      Options for Graylint. Use `graylint --help` to see available options.
      Default: '--color'
    required: false
    default: "--color"
  src:
    description: "Source tree paths to run the linters on. Default: '.'"
    required: false
    default: "."
  version:
    description: 'Version of Graylint to use, e.g. "~=2.0.0", "1.0.0", "@main"'
    required: false
    default: "@main"
  revision:
    description: >-
      Git revision range to compare when determining modified lines.
      Determined automatically if omitted.
    required: false
  lint:
    description: >-
      Comma or space separated list of linters to `pip install` and run from Graylint.
      Optionally, version constraints (using pip syntax) can be specified.
      Example: flake8,pylint==2.13.1
    required: false
    default: ''
  with:
    description: >-
      Run with the given packages installed. This is useful for adding plugins to the
      linters. Use a comma or space separated list.
      Example: "flake8-2020>=1.7 flake8-bugbear>=22.2,!=24.8.19 flake8-comprehensions"
      required: false
      default: ''
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: composite
  steps:
    - name: Commit Range
      id: commit-range
      uses: akaihola/darker/.github/actions/commit-range@1.7.1
    - name: Run Graylint
      run: |
        # Exists since using github.action_path + path to main script doesn't
        # work because bash interprets the backslashes in github.action_path
        # (which are used when the runner OS is Windows) destroying the path to
        # the target file.
        #
        # Also semicolons are necessary because I can't get the newlines to work
        entrypoint="import sys;
        import subprocess;
        from pathlib import Path;

        MAIN_SCRIPT = Path(r'${{ github.action_path }}') / 'action' / 'main.py';

        proc = subprocess.run([sys.executable, str(MAIN_SCRIPT)]);
        sys.exit(proc.returncode)
        "

        pip install 'pip-requirements-parser>=32.0.0'
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo $entrypoint | python
        else
          echo $entrypoint | python3
        fi
      env:
        # TODO: Remove once https://github.com/actions/runner/issues/665 is
        #       fixed.
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_SRC: ${{ inputs.src }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REVISION: ${{ inputs.revision }}
        INPUT_LINT: ${{ inputs.lint }}
        INPUT_WITH: ${{ inputs.with }}
        INPUT_COMMIT_RANGE: ${{ steps.commit-range.outputs.commit-range }}
        pythonioencoding: utf-8
      shell: bash
