---
name: flake8

on: push  # yamllint disable-line rule:truthy

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Graylint's own GitHub action straight from the repository
        uses: ./
        with:
          version: "@${{ github.ref_name }}"
          options: "--color --config pyproject.toml --output-format=github"
          src: src/graylint
          revision: origin/main...
          lint: flake8
          with: >-
            flake8-2020>=1.6.1
            flake8-bugbear>=22.1.11,!=24.8.19
            flake8-comprehensions>=3.7.0
