---
name: pylint

on: push  # yamllint disable-line rule:truthy

# Down scope as necessary via
# https://docs.github.com/en/actions/security-guides
#  /automatic-token-authentication#
#  modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies for running Pylint
        run: |
          pip install -U \
            git+https://github.com/akaihola/darkgraylib.git@main \
            defusedxml \
            pip-requirements-parser>=32.0.0 \
            pygments \
            pylint>=2.13.0 \
            pytest>=6.2.4 \
            requests \
            requests-cache \
            ruamel.yaml \
            toml
          pip list
      - uses: wearerequired/lint-action@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pylint: true
          continue_on_error: false
