---
name: pyupgrade

on: push  # yamllint disable-line rule:truthy

jobs:
  pyupgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/setup.cfg
            **/pyproject.toml
      - name: Ensure modern Python style using pyupgrade
        # TODO: change to `darker[pyupgrade]` after Darker pyupgrade support is released
        run: |
          uvx \
            --with pyupgrade \
            --from 'darker@git+https://github.com/akaihola/darker' \
            darker --formatter=pyupgrade --target-version=py39 --diff
