---
name: Recent Activity Summary
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '12 0 * * *'  # Run every day at 00:12 UTC - change when caught up
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate and Post Repository Summary
        uses: akaihola/repo-summary-post@v0.0.8
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          repo-name: '${{ github.repository }}'
          project-name: 'Graylint'
          # Optional inputs for debugging purposes:
          verbose: '2'
          dry-run: 'false'
          output-content: '-'
        env:
          OPENROUTER_KEY: '${{ secrets.OPENROUTER_KEY }}'
